name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        WITH_V: true
    
    - name: Create Release
      env:
        GITHUB_TOKEN: "${{ secrets.REPO_TOKEN }}"
      run: |
        git clone https://github.com/belalhassan91/angular.git
        cd ./angular
        release_version=$(( git tag | tail -n1 ))
        echo $release_version
        cd ..
        git clone https://github.com/belalhassan91/udacity_Capstone.git
        cd ./udacity_Capstone
        gh release create $release_version ./index/html
